name: Update README
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 10
      - name: Pull in recent blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://blog.andi95.de/en/feed,https://blog.andi95.de/feed"
